- name: Demonstrates use of dictionary variable
  hosts: localhost
  vars:
    - contacts:
          Nitesh:
            name: Nitesh Jeganathan
            mobile: 123-456-7890
  
          Sriram:
            name: Sriram Jeganathan
            mobile: 343-345-3453

  tasks:
    - name: Print contact details
      debug: msg="Contact number of {{item.value.name}} is {{item.value.mobile}}"
      with_dict: "{{contacts}}"
