- name: Demonstrates use of list variable
  hosts: ubuntu
  vars:
    tools:
      - vim
      - tree
      - iputils-ping
  tasks:
   - name: Install the tools
     apt: name="{{item}}" state=latest update_cache=yes
     with_list: "{{tools}}"
